package com.homecare.core.enums;

public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    VALIDATION_FAILED,
    DUPLICATE_EMAIL,
    DUPLICATE_PHONE,
    INVALID_OTP,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    BOOKING_CONFLICT,
    NO_HELPER_AVAILABLE,
    INSUFFICIENT_WALLET_BALANCE,
    BOOKING_CANNOT_BE_CANCELLED,
    HELPER_NOT_AVAILABLE,
    PAYMENT_FAILED,
    TRACKING_NOT_ALLOWED,
    DUPLICATE_REVIEW,
    REVIEW_NOT_ALLOWED,
    INTERNAL_ERROR
}
