package com.homecare.notification.enums;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_ASSIGNED,
    HELPER_EN_ROUTE,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,
    PAYMENT_SUCCESS,
    PAYMENT_REFUND,
    NEW_REVIEW,
    WALLET_LOW,
    SYSTEM_ALERT,
    CHAT_MESSAGE,
    SUBSCRIPTION_STARTED,
    SUBSCRIPTION_RENEWED,
    WALLET_INSUFFICIENT_FOR_RENEWAL,
    SUBSCRIPTION_CANCELLED,
    DISPUTE_RAISED,
    DISPUTE_RESOLVED,
    REFERRAL_SIGNUP_CREDIT,
    REFERRAL_BONUS_CREDIT
}

